[package]
name = "rust-ocaml-starter"
version = "0.1.0"
edition = "2021"

[dependencies]
ocaml = {git = "https://github.com/zshipko/ocaml-rs"}

[build-dependencies]
ocaml-build = {git = "https://github.com/zshipko/ocaml-rs", features=["dune"]}
